### ISSUE TITLE
Use it as view and controller helper.

### ISSUE THREAD

**Issue by martinstiago** [appprova/custom_words#3]
Your gem is just awesome, but I wish to use it on my javascrits and controllers. Can you help me out?

**Comment by jdanielnd** [comment]
We're not requiring the module for now. So you can only do this by calling the class method, using:

`CustomWords::CustomWords.fetch_word(:your_custom_text)`

But it's a good feedback! If you have an idea how to work on that, feel free to submit a PR :)
